name: github-pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: docker://iswai/iswai-docs:latest
        with:
          args: 'build'

      - name: Deploy next
        run: |
          cd build
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add --all
          git commit --allow-empty -m "docs: deploy from ${GITHUB_SHA}"
          git push -f -q https://$(GITHUB_TOKEN)@github.com/${GITHUB_REPOSITORY}.git gh-pages
