name: github-pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: docker://iswai/iswai-docs:latest
        with:
          args: 'build'

      - name: Deploy
        env:
          PERSONAL_TOKEN: ${{ secrets.ISWAI_BOT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build
          SCRIPT_MODE: true
        with:
          emptyCommits: false
        run: |
          wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.5.0/entrypoint.sh
          bash ./entrypoint.sh
